language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=5000
    - MONGODB_URL=mongodb+srv://jones:jones@cluster0.qkysz.mongodb.net/
    - JWT_SECRET=thisisasamplesecretimaggar
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
